name: 24_09_variable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use Workflow input variable
        run: |
          echo "My name is:  ${{ vars.NAME }}"
